services:
  - docker

jobs:
  include:
    - stage: lint & dev build 
      script:
      - docker build --target builder .
    - stage: unit tests
      - docker build --target tester .
    - stage: prod build
      - docker build --target prod . -t "podcast:$TRAVIS_TAG"